# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/rodrigoserracoelho/capi-gateway-entity" }]'
        servers: '[{ "id": "github", "username": "x-access-token", "password": "${{ secrets.TOKEN }}" }]'    
    - name: Publish package
      run: mvn -X --file pom.xml --batch-mode deploy
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
